os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
before_install:
  - 'if [ "$TRAVIS_OS_NAME" = ''osx'' ]; then export PATH=/usr/bin:$PATH; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
script:
  - 'npm run test:unit'
  - 'export DEBUG=testing:*'
  - 'npm run test:integration'
# env:
#   - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # - g++-4.9
      - bluetooth
      - bluez
      - libbluetooth-dev
      - libudev-dev
